name: Deploy to EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: |
          client/package-lock.json
          server/package-lock.json
    
    - name: Install client dependencies
      run: |
        cd client
        npm ci
    
    - name: Build client
      run: |
        cd client
        echo "VITE_SERVER_URL=http://kelvinnewton.com/api/quartoclone" > .env
        npm run build
    
    - name: Install server dependencies
      run: |
        cd server
        npm ci
    
    - name: Deploy to EC2
      if: github.ref == 'refs/heads/main'
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          # Navigate to app directory
          cd /home/ubuntu/quartoclone
          
          # Stash any local changes and pull latest changes
          git stash
          git pull origin main
          
          # Install/update server dependencies
          cd server
          npm ci --production
          
          # Install/update client dependencies and build
          cd ../client
          npm ci
          echo "VITE_SERVER_URL=http://kelvinnewton.com/api/quartoclone" > .env
          npm run build
          
          # Copy built files to nginx web directory
          sudo mkdir -p /var/www/quartoclone
          sudo cp -r dist/* /var/www/quartoclone/
          sudo chown -R www-data:www-data /var/www/quartoclone
          
          # Restart services
          # Kill existing processes
          sudo pkill -f "serve -s dist -l 80" || true
          sudo pkill -f "node index.js" || true
          
          # Wait a moment for processes to fully stop
          sleep 2
          
          # Start server
          cd /home/ubuntu/quartoclone/server
          nohup node index.js > server.log 2>&1 &
          
          # Restart nginx to serve updated files
          sudo systemctl restart nginx
          
          echo "Deployment completed successfully!"